# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='invalid',
            field=models.BooleanField(default=False),
        ),
    ]
