# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpsed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('line_memo', models.TextField(blank=True, null=True)),
                ('invalid', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpsed.Product')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_user', models.CharField(max_length=60)),
                ('ord_date', models.DateField()),
                ('effective_date', models.DateField()),
                ('invalid', models.BooleanField(default=False)),
                ('memo', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpsed.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='quotedetail',
            name='quotehead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpsed.QuoteHead'),
        ),
    ]
