# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpsed', '0002_auto_20160805_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotedetail',
            name='line_memo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
