# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dpsed', '0004_auto_20160808_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCtrlOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=36)),
                ('invalid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ZmmsOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=36)),
                ('invalid', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='cyclestatus',
            name='invalid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='material_ctrl',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dpsed.MaterialCtrlOption'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workorder',
            name='recevice_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='zmms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpsed.ZmmsOption'),
        ),
    ]
