# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpsed', '0006_auto_20160809_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='comfirm',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='workday',
        ),
    ]
