# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 11:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dpsed', '0008_auto_20160809_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=36)),
                ('order_squence', models.IntegerField(default=1000)),
                ('invalid', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='workorder',
            name='order_category',
            field=models.ForeignKey(default=datetime.datetime(2016, 8, 9, 11, 24, 43, 866094, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='dpsed.OrderCategory'),
            preserve_default=False,
        ),
    ]
