# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpsed', '0011_workorder_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='category',
        ),
    ]
