# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpsed', '0012_remove_workorder_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderCategory',
        ),
    ]
