# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpsed', '0014_ordercategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dpsed.OrderCategory'),
            preserve_default=False,
        ),
    ]
