# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpsed', '0015_workorder_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='ships_order',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
